const $=s=>document.querySelector(s);let category='전체 답변',selected=2,query='',values={},drafts={};let timer;const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const synonyms={결재:'결제',송금:'입금',가격표:'가격',금액:'가격',납기:'제작',재질:'원단',소재:'원단',서배협:'서대문구배구협회',구글폼:'주문서'};
function matches(r,q){const hay=(r.slice(1).join(' ')).toLowerCase().replace(/\s/g,'');return q.trim().toLowerCase().split(/\s+/).every(t=>hay.includes(t)||hay.includes(synonyms[t]||t));}
function filtered(){return rows.filter(r=>(category==='전체 답변'||r[1]===category)&&matches(r,query));}
function fields(r){return [...new Set([...r[4].matchAll(/\[([^\]]+)\]/g)].map(m=>m[1]))];}
function rendered(r){const v=drafts[r[0]]||{};return r[4].replace(/\[([^\]]+)\]/g,(s,k)=>(v[k]||'').trim()||s);}
function nav(){ $('#categories').innerHTML=categories.map(c=>`<button class="nav-btn ${category===c?'active':''}" aria-pressed="${category===c}" data-category="${esc(c)}">${c}<span>${c==='전체 답변'?rows.length:rows.filter(r=>r[1]===c).length}</span></button>`).join('');}
function refresh(){nav();const found=filtered();if(!found.some(r=>r[0]===selected))selected=found[0]?.[0]||null;$('#clear').hidden=!query;$('#resultTitle').textContent=query?'검색 결과':category;$('#resultCount').textContent=found.length+'개';$('#list').innerHTML=found.length?found.map(r=>`<button class="item ${selected===r[0]?'active':''}" data-id="${r[0]}" aria-pressed="${selected===r[0]}"><div class="item-meta"><span>${r[1]}</span><span class="item-no">${String(r[0]).padStart(2,'0')}</span></div><strong>${r[2]}</strong><p>${esc(r[3].split(' ').slice(0,5).join(' · '))}</p></button>`).join(''):'<div class="empty">일치하는 답변이 없습니다.<br>짧은 단어로 다시 검색해 보세요.<br><button id="resetSearch">전체 답변 보기</button></div>';detail();}
function detail(){const r=rows.find(r=>r[0]===selected);if(!r){$('#detail').innerHTML='<div class="guide-empty">질문이나 단어를 검색하고<br>왼쪽 목록에서 답변을 선택하세요.</div>';return;}const keys=fields(r);$('#detail').innerHTML=`<div class="detail-head"><div class="detail-meta"><span class="pill">${r[1]}</span>${r[6]?`<span class="pill warn">${r[6]}</span>`:''}${keys.length?'<span class="pill warn">내용 입력 필요</span>':''}</div><h2>${r[2]}</h2></div><div class="detail-body"><div class="memo"><strong>내부 확인 · 고객에게 복사되지 않아요</strong>${r[5]}</div>${[29,30,31,32].includes(r[0])?'<a class="work-order-download" href="customer-work-order.xlsx" download="작업지시서_고객용.xlsx">↓ 고객용 작업지시서 다운로드 <span>XLSX · 카톡에 파일 첨부</span></a>':''}${keys.length?`<div class="fields">${keys.map(k=>`<label>${esc(k)}<input data-field="${esc(k)}" value="${esc(drafts[r[0]]?.[k]||'')}" placeholder="${esc(k)} 입력" autocomplete="off"></label>`).join('')}</div>`:''}<div class="reply-label"><span>고객에게 보낼 답변</span><span>카카오톡 붙여넣기용</span></div><div class="reply" id="reply"></div><div class="copybar"><button class="copy" id="copy">답변 복사</button>${keys.length?'<button class="reset" id="resetFields">입력 초기화</button>':''}</div><p class="hint">${keys.length?'빈칸을 채우면 답변에 자동 반영됩니다. 입력 내용은 새로고침 시 초기화됩니다.':'답변 문구만 복사됩니다. 내부 메모와 제목은 포함되지 않습니다.'}</p><div id="manual"></div></div>`;reply();}
function reply(){const r=rows.find(r=>r[0]===selected);$('#reply').innerHTML=esc(rendered(r)).replace(/\[([^\]]+)\]/g,'<mark>[$1]</mark>');}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
async function copy(){const r=rows.find(r=>r[0]===selected);const missing=fields(r).filter(k=>!(drafts[r[0]]?.[k]||'').trim());if(missing.length){toast(missing.join(', ')+'을(를) 먼저 입력해 주세요.');[...document.querySelectorAll('[data-field]')].find(e=>e.dataset.field===missing[0])?.focus();return;}const text=rendered(r);let ok=false;try{await navigator.clipboard.writeText(text);ok=true;}catch{const t=document.createElement('textarea');t.value=text;t.style.cssText='position:fixed;left:-9999px';document.body.append(t);t.select();try{ok=document.execCommand('copy')}catch{}t.remove();}if(ok){toast('답변이 복사되었습니다. 카톡에 붙여넣어 주세요.');$('#copy').textContent='✓ 복사 완료';setTimeout(()=>{if($('#copy'))$('#copy').textContent='답변 복사'},1800);}else{$('#manual').innerHTML='<div class="manual"><p>자동 복사를 사용할 수 없습니다. 아래 문구를 선택해 복사해 주세요.</p><textarea aria-label="직접 복사할 답변" readonly></textarea></div>';const t=$('#manual textarea');t.value=text;t.focus();t.select();}}
$('#search').addEventListener('input',e=>{query=e.target.value;refresh()});document.addEventListener('input',e=>{if(e.target.dataset.field){drafts[selected]||={};drafts[selected][e.target.dataset.field]=e.target.value;reply();}});document.addEventListener('click',e=>{const cat=e.target.closest('[data-category]'),item=e.target.closest('[data-id]'),chip=e.target.closest('[data-query]');if(cat){category=cat.dataset.category;refresh();}else if(item){selected=Number(item.dataset.id);refresh();if(innerWidth<=620)$('#detail').scrollIntoView({behavior:'smooth',block:'start'});}else if(chip){category='전체 답변';query=chip.dataset.query;$('#search').value=query;refresh();}else if(e.target.id==='clear'||e.target.id==='resetSearch'){query='';$('#search').value='';if(e.target.id==='resetSearch')category='전체 답변';refresh();$('#search').focus();}else if(e.target.id==='copy')copy();else if(e.target.id==='resetFields'){delete drafts[selected];detail();}});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus();}if(e.key==='Escape'&&document.activeElement===$('#search')){query='';$('#search').value='';refresh();}});refresh();
